### ISSUE TITLE
Modal Context

### ISSUE THREAD

**Issue by xSallus** [RandelFreitas/modal#1]
No Contexto do Modal, é passado ao Provider, uma constante  value que contém: open e openModal.

No entanto, quando a função useModal é chamada, está sendo desestruturada como open e openModal, quando deveria ser value...

Onde está assim:
const {open, openModal} = useModal()

Deveria estar assim:
const {value} = useModal()

Espero ter ajudado! :D

**Comment by RandelFreitas** [comment]
Obrigado, ajudou sim :D

**Comment by xSallus** [comment]
Nada, tmj :D
